"""
Generate embeddings for landmark names
"""
import os
import argparse
import json
from pathlib import Path
import openai

from gpt3 import GPT3
from utils import save_to_file

openai.api_key = os.getenv("OPENAI_API_KEY")


def load_names(fpath):
    """
    Load names of known objects in given environment.
    Assume 1 name per line in txt file, e.g. data/osm/osm_landmarks_corlw.txt
    Assume 1 dictionary of key: landmark name, value: semantic info in json file, e.g. data/osm/lmks/boston.json
    """
    ftype = os.path.splitext(fpath)[-1][1:]
    if ftype == "txt":
        with open(fpath, 'r') as rf:
            names = [line.strip() for line in rf.readlines()]
    elif ftype == "json":
        with open(fpath, 'r') as rfile:
            names = json.load(rfile).keys()
    else:
        raise ValueError(f"ERROR: file type {ftype} not recognized")
    return names


def store_embeds(model, lmk_path, gpt3_embed_engine=None):
    names = load_names(lmk_path)

    if model == "gpt3":
        ground_module = GPT3(gpt3_embed_engine)
    # elif model == 'bert':
    #     ground_module = BERT()
    else:
        raise ValueError("ERROR: grounding module not recognized")

    name2embed = {name: ground_module.get_embedding(name) for name in names}

    lmk_fname = Path(lmk_path).stem
    if model == "gpt3":
        save_fpath = f"data/osm/lmk_embeds/obj2embed_{lmk_fname}_{gpt3_embed_engine}.pkl"
    else:
        save_fpath = f"data/osm/lmk_embeds/obj2embed_{lmk_fname}_{model}.pkl"
    save_to_file(name2embed, save_fpath)
    return save_fpath


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--lmk_path", type=str, default="data/osm/lmks", help="fpath or dpath to lmks.")
    parser.add_argument("--model", type=str, default="gpt3", choices=["gpt3", "bert"])
    parser.add_argument("--gpt3_embed_engine", type=str, default="text-embedding-ada-002")
    args = parser.parse_args()

    if os.path.isdir(args.lmk_path):
        lmk_paths = [os.path.join(args.lmk_path, fname) for fname in os.listdir(args.lmk_path) if "json" in fname and "boston" not in fname]
    else:
        lmk_paths = [args.lmk_path]

    for idx, lmk_path in enumerate(lmk_paths):
        print(f"generating landmark embedding for {Path(lmk_path).stem}")
        save_fpath = store_embeds(args.model, lmk_path, args.gpt3_embed_engine)
        print(f"{idx}: embeddings generated by {args.model} model, stored at {save_fpath}")
